<div id="div_redes_sociais">
    <h4 class="ui horizontal divider inverted header">
        Nossas Redes Sociais
    </h4>
    <center>
        <div class="ui container">
            <a href="https://web.facebook.com/SECCIM/" target="_new"><i class="big facebook icon"></i></a>
            <a href="https://instagram.com/seccim_ufrrj?igshid=q81oksmreoml" target="_new"><i class="big instagram icon"></i></a>
            <a href="https://twitter.com/seccim_ufrrj" target="_new"><i class="big twitter icon"></i></i></a>
        </div>
    </center>
</div>
<div id="div_footer">
    <p>© SECCIM-2019 – Universidade Federal Rural do Rio de Janeiro</p>
</div>
