<meta charset="utf-8">
<!-- <base href="seccim/"> -->
<link rel="stylesheet" type="text/css" href="semantic/semantic.min.css">
<link rel="stylesheet" type="text/css" href="css/seccim.css">
<link href="https://fonts.googleapis.com/css?family=Lato|Poppins&display=swap" rel="stylesheet">
<link rel="shortcut icon" type="image/png" href="img/favicon.png"/>

<script
    src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
    crossorigin="anonymous"></script>
<script src="semantic/semantic.min.js"></script>
<script src="js/seccim.js"></script>
<?php include "includes/links.php"; ?>

<meta name="viewport" content="width=device-width,maximum-scale=1">
<meta name="robots" content="index, follow, noarchive">
<meta id="SiteOwner" content="SECCIM" name="owner"></meta>
<meta id="SiteSubject" name="subject" content="Computação"></meta>
<meta id="SiteAbstract" name="abstract" content="Semana Acadêmica de Ciência da Computação - UFRRJ"></meta>
<meta id="SiteCopyright" content="© SECCIM-2019 – Universidade Federal Rural do Rio de Janeiro" name="copyright"></meta>
<meta name="author" content="SECCIM">
<meta name="DC.creator" content="SECCIM" />
<meta name="DC.publisher" content="SECCIM" />
<meta name="Custodian" content="SECCIM" />
<meta property="og:locale" content="pt_BR">
<meta property="og:site_name" content="SECCIM">
